SORT_DROPDOWN = ".product_sort_container"
ADD_TO_CART_1 = "#add-to-cart-sauce-labs-backpack"
ADD_TO_CART_2 = "#add-to-cart-sauce-labs-bike-light"
REMOVE_FROM_CART_1 = "#remove-sauce-labs-backpack"
REMOVE_FROM_CART_2 = "#remove-sauce-labs-bike-light"
SHOPPING_CART = ".shopping_cart_link"
SHOPPING_CART_BADGE = ".shopping_cart_badge"
INVENTORY_LIST = "#inventory_container > div"
